name: musily_repository
description: Music metadata repository for musily.
version: 2.0.1
pubish_to: 'none'
repository: https://github.com/MusilyApp/musily_repository

environment:
  sdk: ^3.4.3

dependencies:
  crypto: ^3.0.3
  dart_ytmusic_api: ^1.0.7
  dart_spotify_api:
    git:
      url: https://github.com/MusilyApp/dart_spotify_api.git
  shared_preferences: ^2.3.2
  youtube_explode_dart: ^2.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
