name: musily_repository
description: Music metadata repository for musily.
version: 1.0.0
pubish_to: 'none'
repository: https://github.com/MusilyApp/musily_repository

environment:
  sdk: ^3.4.3

dependencies:
  crypto: ^3.0.3
  # path: ^1.8.0
  dart_ytmusic_api:
    git:
      url: https://github.com/MusilyApp/dart_ytmusic_api.git

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
